[package]
name = "manage-system"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
rfd = "0.15.4"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.43", features = ["derive"] }
rpassword = "7.4.0"
serde_json = "1.0.142"
unicode-width = "0.2.1"
